from Seq0 import *
print("\n---EXERCISE 6---\n")
print("Gene U5:")
seq_reverse("../Genome Sequences/U5.fa", 20)
print("Gene ADA:")
seq_reverse("../Genome Sequences/ADA.fa", 20)
print("Gene FRAT1:")
seq_reverse("../Genome Sequences/FRAT1.fa", 20)
print("Gene FXN:")
seq_reverse("../Genome Sequences/FXN.fa", 20)
