from Seq0 import *
print("\n---EXERCISE 7---\n")
print("Gene U5:")
seq_complement("../Genome Sequences/U5.fa")
print("Gene ADA:")
seq_complement("../Genome Sequences/ADA.fa")
print("Gene FRAT1:")
seq_complement("../Genome Sequences/FRAT1.fa")
print("Gene FXN:")
seq_complement("../Genome Sequences/FXN.fa")
