from Seq0 import *
print("\n---EXERCISE 8---\n")
print("Gene U5:")
most_frequent_base("../Genome Sequences/U5.fa")
print("Gene ADA:")
most_frequent_base("../Genome Sequences/ADA.fa")
print("Gene FRAT1:")
most_frequent_base("../Genome Sequences/FRAT1.fa")
print("Gene FXN:")
most_frequent_base("../Genome Sequences/FXN.fa")